development:
  adapter: postgresql
  encoding: unicode
  database: budget_app_development
  host: localhost
  pool: 5
  username: postgres
  password: koko23052020

test:
  adapter: postgresql
  encoding: unicode
  database: budget_app_test
  pool: 5
  username: postgres
  password: koko23052020

production:
  adapter: postgresql
  encoding: unicode
  database: budget_app_production
  pool: 5
  username: postgres
  password: koko23052020

